%% ================================================================
%% Indian Road Capacity Analyzer — Digital Twin Builder
%% create_digital_twin_model.m
%%
%% Run this script ONCE in MATLAB R2024a/R2026a to generate
%% the Simulink model file  road_digital_twin.slx
%%
%% After the .slx file is created, use run_digital_twin.m to
%% actually simulate and export results to the web dashboard.
%% ================================================================

clc; clear; close all;
fprintf('Building Digital Twin Simulink model...\n');

MODEL_NAME = 'road_digital_twin';

%% ---- close existing open copy so we can overwrite cleanly ----
if bdIsLoaded(MODEL_NAME)
    close_system(MODEL_NAME, 0);
end

%% ---- create blank model ----
new_system(MODEL_NAME);
open_system(MODEL_NAME);

%% ================================================================
%% SUBSYSTEM LAYOUT  (pixel positions for the Simulink canvas)
%%
%%  [Ideal Road Subsystem]   [Defect Road Subsystem]
%%       |                          |
%%  [Ideal Capacity Out]    [Defect Capacity Out]
%%       \                         /
%%        ----> [Mux] --> [To File / To Workspace]
%% ================================================================

%% ---- helper: position array [left top right bottom] ----
POS = @(x,y,w,h) [x, y, x+w, y+h];

%% ================================================================
%% BLOCK 1: Simulation Clock  (so plots have a time axis in seconds)
%% ================================================================
add_block('simulink/Sources/Clock', [MODEL_NAME '/Clock'], ...
    'Position', POS(30, 50, 30, 30));

%% ================================================================
%% BLOCK 2: Road Configuration (From Workspace)
%%   MATLAB populates a struct "road_cfg" before sim starts.
%%   Simulink reads it so the model is data-driven, not hardcoded.
%% ================================================================
add_block('simulink/Sources/From Workspace', ...
    [MODEL_NAME '/RoadConfig_ideal_DSV'], ...
    'VariableName', 'simIn.ideal_dsv', ...
    'Position', POS(30, 130, 120, 30), ...
    'Interpolate', 'off');

add_block('simulink/Sources/From Workspace', ...
    [MODEL_NAME '/RoadConfig_defect_DSV'], ...
    'VariableName', 'simIn.defect_dsv', ...
    'Position', POS(30, 200, 120, 30), ...
    'Interpolate', 'off');

add_block('simulink/Sources/From Workspace', ...
    [MODEL_NAME '/RoadConfig_cap_loss_pct'], ...
    'VariableName', 'simIn.cap_loss_pct', ...
    'Position', POS(30, 270, 120, 30), ...
    'Interpolate', 'off');

add_block('simulink/Sources/From Workspace', ...
    [MODEL_NAME '/RoadConfig_los_numeric'], ...
    'VariableName', 'simIn.los_numeric', ...
    'Position', POS(30, 340, 120, 30), ...
    'Interpolate', 'off');

add_block('simulink/Sources/From Workspace', ...
    [MODEL_NAME '/RoadConfig_pothole_speed_impact'], ...
    'VariableName', 'simIn.pothole_speed_pct', ...
    'Position', POS(30, 410, 120, 30), ...
    'Interpolate', 'off');

%% ================================================================
%% BLOCK 3: Transfer Function  —  Traffic Flow Dynamics
%%   Models how traffic flow responds to capacity (first-order lag).
%%   Ideal road:  fast response  (τ = 5s)
%%   Defect road: sluggish response (τ = 30s, higher delay)
%% ================================================================

%% Ideal road flow dynamics
add_block('simulink/Continuous/Transfer Fcn', ...
    [MODEL_NAME '/IdealFlow_TF'], ...
    'Numerator', '[1]', ...
    'Denominator', '[5 1]', ...
    'Position', POS(230, 130, 100, 40));

%% Defect road flow dynamics (heavier lag = congestion buildup)
add_block('simulink/Continuous/Transfer Fcn', ...
    [MODEL_NAME '/DefectFlow_TF'], ...
    'Numerator', '[1]', ...
    'Denominator', '[30 1]', ...
    'Position', POS(230, 200, 100, 40));

%% ================================================================
%% BLOCK 4: Pothole Speed Degradation
%%   Vehicle speed = Vfree * (1 - pothole_speed_impact/100)
%%   Using a Gain block to scale.
%% ================================================================

%% Free-flow speed constant (50 km/h urban arterial default — IRC:106)
add_block('simulink/Sources/Constant', ...
    [MODEL_NAME '/FreeFlowSpeed_kmh'], ...
    'Value', '50', ...
    'Position', POS(30, 490, 80, 30));

%% Convert pct_impact to fraction
add_block('simulink/Math Operations/Gain', ...
    [MODEL_NAME '/PotholeImpact_Gain'], ...
    'Gain', '0.01', ...
    'Position', POS(230, 410, 60, 30));

%% 1 - fraction
add_block('simulink/Math Operations/Sum', ...
    [MODEL_NAME '/SpeedFactor_Sum'], ...
    'Inputs', '+-', ...
    'Position', POS(350, 480, 40, 40));

add_block('simulink/Sources/Constant', ...
    [MODEL_NAME '/Unity'], ...
    'Value', '1', ...
    'Position', POS(230, 490, 60, 30));

%% Vehicle speed (km/h) = FreeFlowSpeed * SpeedFactor
add_block('simulink/Math Operations/Product', ...
    [MODEL_NAME '/VehicleSpeed_Product'], ...
    'Position', POS(450, 475, 60, 40));

%% ================================================================
%% BLOCK 5: LOS  Staircase — maps LOS numeric to label
%%   LOS A=1, B=2, C=3, D=4, E=5, F=6  (integer from Python bridge)
%%   Lookup Table saturates: ensures output stays 1-6.
%% ================================================================
add_block('simulink/Lookup Tables/1-D Lookup Table', ...
    [MODEL_NAME '/LOS_Lookup'], ...
    'BreakpointsForDimension1', '[1 2 3 4 5 6]', ...
    'Table',                    '[1 2 3 4 5 6]', ...
    'ExtrapMethod', 'Clip', ...
    'Position', POS(230, 340, 100, 40));

%% ================================================================
%% BLOCK 6: Mux all signals → single bus → To Workspace
%% ================================================================
add_block('simulink/Signal Routing/Mux', ...
    [MODEL_NAME '/OutputMux'], ...
    'Inputs', '5', ...
    'Position', POS(600, 150, 30, 350));

%% ---- To Workspace (saves to base WS so run_digital_twin.m can read) ----
add_block('simulink/Sinks/To Workspace', ...
    [MODEL_NAME '/SimOut'], ...
    'VariableName', 'dt_simout', ...
    'SampleTime',  '-1', ...
    'SaveFormat',  'Structure With Time', ...
    'Position', POS(680, 290, 100, 40));

%% ================================================================
%% BLOCK 7: Scopes — 2 visual scopes for MATLAB-side display
%% ================================================================
add_block('simulink/Sinks/Scope', ...
    [MODEL_NAME '/Scope_Capacity'], ...
    'NumInputPorts', '2', ...
    'Position', POS(680, 130, 60, 60));

add_block('simulink/Sinks/Scope', ...
    [MODEL_NAME '/Scope_Speed'], ...
    'NumInputPorts', '1', ...
    'Position', POS(680, 220, 60, 60));

%% ================================================================
%% WIRING  —  connect all blocks
%% ================================================================

%% Road config → Transfer Functions
add_line(MODEL_NAME, 'RoadConfig_ideal_DSV/1',       'IdealFlow_TF/1');
add_line(MODEL_NAME, 'RoadConfig_defect_DSV/1',      'DefectFlow_TF/1');
add_line(MODEL_NAME, 'RoadConfig_cap_loss_pct/1',    'OutputMux/3');
add_line(MODEL_NAME, 'RoadConfig_los_numeric/1',     'LOS_Lookup/1');
add_line(MODEL_NAME, 'RoadConfig_pothole_speed_impact/1', 'PotholeImpact_Gain/1');

%% Transfer Function outputs → Mux
add_line(MODEL_NAME, 'IdealFlow_TF/1',   'OutputMux/1');
add_line(MODEL_NAME, 'DefectFlow_TF/1',  'OutputMux/2');

%% LOS → Mux
add_line(MODEL_NAME, 'LOS_Lookup/1',     'OutputMux/4');

%% Speed degradation chain
add_line(MODEL_NAME, 'PotholeImpact_Gain/1', 'SpeedFactor_Sum/2');
add_line(MODEL_NAME, 'Unity/1',              'SpeedFactor_Sum/1');
add_line(MODEL_NAME, 'FreeFlowSpeed_kmh/1',  'VehicleSpeed_Product/1');
add_line(MODEL_NAME, 'SpeedFactor_Sum/1',    'VehicleSpeed_Product/2');
add_line(MODEL_NAME, 'VehicleSpeed_Product/1', 'OutputMux/5');

%% Mux → outputs
add_line(MODEL_NAME, 'OutputMux/1', 'SimOut/1');

%% Scope connections (tapped from Mux input lines)
add_line(MODEL_NAME, 'IdealFlow_TF/1',       'Scope_Capacity/1');
add_line(MODEL_NAME, 'DefectFlow_TF/1',      'Scope_Capacity/2');
add_line(MODEL_NAME, 'VehicleSpeed_Product/1', 'Scope_Speed/1');

%% ================================================================
%% MODEL SETTINGS
%% ================================================================
set_param(MODEL_NAME, ...
    'StopTime',        '60', ...
    'Solver',          'ode45', ...
    'MaxStep',         '0.5', ...
    'SaveTime',        'on', ...
    'SaveOutput',      'on', ...
    'SignalLogging',   'on', ...
    'SignalLoggingName','logsout');

%% ================================================================
%% SAVE
%% ================================================================
save_system(MODEL_NAME, [MODEL_NAME '.slx']);
fprintf('Model saved as  %s.slx\n', MODEL_NAME);
fprintf('Next step: run  run_digital_twin.m\n');
